use_frameworks!

target 'SVisualData_Example' do
  pod 'SVisualData', :path => '../'

  target 'SVisualData_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
